### ISSUE TITLE
Erro de autenticação via token

### ISSUE THREAD

**Issue by FlatanSilvio** [enterplug/consulta-enterplug#13]
Autenticação:

**Comment by rodrigooler** [comment]
@FlatanSilvio caso esteja com dificuldades de criar a issue entre no chat https://gitter.im/consulta-enterplug/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link que eu te auxílio.

**Comment by FlatanSilvio** [comment]
Autenticação:
    private String getToken(String pEMail, String pPassW) {

```
    HttpResponse<String> hTTP  = null;
    HttpHost             hHOST = null;

    if ( HttpProxy.length() > 0 ) {
        hHOST = new HttpHost(HttpProxy, Integer.parseInt(HttpProxyPORT));
    } 

    String retTK = "TOKEN INVÁLIDO";

    try {

        if ( HttpProxy.length() > 0 ) {
            Unirest.setProxy(hHOST);
        }

        hTTP = Unirest.post("http://186.249.34.34/auth")
                  .header("content-type", "application/json")
                  .header("cache-control", "no-cache")
                  .body("{\n    \"email\": \"" + pEMail + "\",\n    \"password\": \"" + pPassW + "\"\n}")
                  .asString();

        String S = hTTP.getBody();

        if (S.length() > 0 && !S.contains("DENIED") && !S.contains("ERRO")) {
            JSONObject jsTK = new JSONObject(S);
            retTK = jsTK.getString("token");
        }

    } catch (UnirestException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } catch (JSONException jj) {
        jj.printStackTrace();
    }

    return retTK;

}
```

Retorna o TOKEN.

Consulta:
    private String getCons233() {

```
    String s233 = 
        "{\n" +
            "  \"codigoProduto\":" + " \"233\"" + ",\n" +
            "  \"tipoConsumidor\":" + " \"F\"" + ",\n" +
            "  \"documentoConsumidor\":" + " \"42924057191\"" + ",\n" +
            "  \"telefoneConsultar\":" + " {   \n" +
                "    \"ddd\":" + " \"16\"" + ",\n" +
                "    \"numero\":" + " \"999999999\"\n" +
            "  },\n" +
            "  \"cepConsumidor\":" + " \"14401360\"" + ",\n" +
            "  \"cepOrigem\":" + " \"14401360\"" + ",\n" +
            "  \"codigoEstacaoConsultante\":" + " \"123\"\n" +
        "}";

    System.out.println(s233);

    String ret233 = execConsulta(s233);

    return ret233;

}
private String execConsulta( String pCons ) {

    HttpResponse<String> hTTP = null;
    String retCON = "";

    try {
```

/\*          if ( HttpProxy.length() > 0 ) {
                Unirest.setProxy(hHOST);
            }
*/  
            hTTP = Unirest.post("http://186.249.34.34/api/consulta")
                      .header("content-type", "application/json")
                      .header("authorization", "Bearer " + wsTOKEN + "\"")
                      .header("cache-control", "no-cache")
                      .body(pCons)
                      .asString();

```
        retCON = hTTP.getBody();

    } catch (UnirestException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } catch (JSONException jj) {
        jj.printStackTrace();
    }

    return retCON;

}
```

Retorna:
{"exception":"io.jsonwebtoken.SignatureException",
"path":"/api/consulta",
"error":"Internal Server Error",
"message":"Token não autorizado,
 efetue o login novamente para efetuar a geração de um token válido.",
"timestamp":1474030974813,
"status":500}

**Comment by rodrigooler** [comment]
Modifique o header authorization conforme abaixo e tente executar novamente o método:

Código enviado por você : .header("authorization", "Bearer " + wsTOKEN + "\"")
Código modificado:  .header("authorization", "Bearer " + wsTOKEN)

**Comment by FlatanSilvio** [comment]
É isso mesmo, uma Aspa a mais...

**Comment by FlatanSilvio** [comment]
Retornou certinho...
Valeu.

**Comment by rodrigooler** [comment]
Perfeito @FlatanSilvio caso tenha mais alguma dúvida ou erro fique a vontade para criar as issues. 

Atenciosamente.
